In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3]) # 1, 2, 3, 4
print(type(arr1));print(arr1.shape)

arr2 = np.array([[1,2,3],[4,5,6]])
print(type(arr2));print(arr2.shape)

arr3 = np.array([[1,2,3]]) # (1,2,3)
print(type(arr3));print(arr3.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [ ]:
print(f'각각{arr1.ndim}, {arr2.ndim}, {arr3.ndim}차원')

각각1, 2, 2차원


In [ ]:
lst1 = [1,2,3]
print(type(lst1))
print(type(np.array(lst1)))
print(np.array(lst1).dtype)

<class 'list'>
<class 'numpy.ndarray'>
int64


# int32와 int64의 차이는 나타낼 수 있는 정수를 나타낸다
int32 : $(-2^{32})$ 부터 $(2^{32}-1)$

int64 : $(-2^{64})$ 부터 $(2^{64}-1)$

In [ ]:
lst2 = [1,2,'test']
print(type(lst2))
print(type(np.array(lst2)))
print(np.array(lst2).dtype)

<class 'list'>
<class 'numpy.ndarray'>
<U21


# "<U21"는 유니코드 문자열을 뜻한다
"<UXX"에서 XX는 실행환경에 따라서 달라질 수 있다
(참조하는 메모리의 숫자를 나타내는 것으로 보임)

In [ ]:
lst3 = [1,2,3.1]
print(type(lst3))
print(type(np.array(lst3)))
print(np.array(lst3).dtype)

<class 'list'>
<class 'numpy.ndarray'>
float64


In [ ]:
lst4 = [1.1, 2.2, 3.3]
arr4 = np.array(lst4)
print(arr4, arr4.dtype)

[1.1 2.2 3.3] float64


In [ ]:
arr5 = arr4.astype('int64')
print(arr5, arr5.dtype)

[1 2 3] int64


In [ ]:
arr6 = np.arange(1,10)
print(arr6, arr6.dtype, arr6.shape)

[1 2 3 4 5 6 7 8 9] int64 (9,)


In [ ]:
arr7 = np.zeros((3,2),dtype='int64')
print(arr7, arr7.dtype, arr7.shape)

[[0 0]
 [0 0]
 [0 0]] int64 (3, 2)


In [ ]:
arr8 = np.ones((3,2))
print(arr8, arr8.dtype, arr8.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)


In [ ]:
arr8.reshape(2,3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr8.reshape(-1,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
type(arr8.tolist())
# ndarray => list

list

# Indexing

In [ ]:
arr9 = np.arange(1,10)
arr9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr9[4]

5

In [ ]:
arr9[-2]

8

In [ ]:
arr9[4] = 10
arr9

array([ 1,  2,  3,  4, 10,  6,  7,  8,  9])

In [ ]:
arr10 = np.arange(10).reshape(-1,5)
arr10

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr10[1,1]

6

In [ ]:
arr10[1,1] = 10
arr10

array([[ 0,  1,  2,  3,  4],
       [ 5, 10,  7,  8,  9]])

# Slicing

In [ ]:
arr11 = np.arange(1,10)
arr11

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr11[0:3]

array([1, 2, 3])

In [ ]:
arr11[:5]

array([1, 2, 3, 4, 5])

In [ ]:
arr11[3:]

array([4, 5, 6, 7, 8, 9])

In [ ]:
arr11[:]

140435403397904 140435403397904


In [ ]:
arr12 = np.arange(1,10).reshape(3,3)
arr12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr12[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
arr12[1:3, 0:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr12[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr12[:, :] #=arr12[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr12[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr12[:2, 0]

array([1, 4])

# Fancy Indexing

In [ ]:
arr12[[0,1],2]

array([3, 6])

In [ ]:
arr12[[0,1], 0:2]

array([[1, 2],
       [4, 5]])

# Boolean Indexing

In [ ]:
arr13 = np.arange(1,10)
arr13

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr13[arr13 > 5]

array([6, 7, 8, 9])

In [ ]:
arr13 > 5

array([False, False, False, False, False,  True,  True,  True,  True])

# sort(), argsort()

In [ ]:
arr14 = np.array([3,1,9,5])
arr14

array([3, 1, 9, 5])

In [ ]:
print("정렬:",np.sort(arr14))
print("원본:", arr14)

정렬: [1 3 5 9]
원본: [3 1 9 5]


In [ ]:
print("정렬:",arr14.sort())
print("원본:", arr14)

정렬: None
원본: [1 3 5 9]


In [ ]:
arr14 = np.array([3,1,9,5])
arr14

array([3, 1, 9, 5])

In [ ]:
np.sort(arr14)[::-1]

array([9, 5, 3, 1])

In [ ]:
arr15 = np.array([[3,5],[8,2]])
arr15

array([[3, 5],
       [8, 2]])

In [ ]:
np.sort(arr15, axis=0)

array([[3, 2],
       [8, 5]])

In [ ]:
np.sort(arr15, axis=1)

array([[3, 5],
       [2, 8]])

In [ ]:
arr14 = np.array([3,1,9,5])
arr14

array([3, 1, 9, 5])

In [ ]:
np.argsort(arr14)

array([1, 0, 3, 2])

In [ ]:
np.argsort(arr14)[::-1]

array([2, 3, 0, 1])

# 내적

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

In [ ]:
np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

In [ ]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

# 2022년 07월 21일 머신러닝 교재 실습 스터디
## 참여자 : 홍지민, 최정필, 남궁연범, 배성현


- Numpy라이브러리 설치 및 교재 실습
  - ndarray 와 list의 Type 차이 확인
  - Numpy에서의 Indexing Slicing하기
  - sort, argsort를 이용한 배열 정렬
  - 행렬 내적 및 전치행렬 구하기

- 1차 스터디 기간동안 구체적인 목표 정하기
  - 교재의 2장 마지막까지 해보기
  (타이타닉 생존자 예측)